In [ ]:
import pandas as pd 
import numpy as np

In [9]:
df = pd.DataFrame({
    "name":  ["Ace", "Riya", "Sam", "Tina", "Raj"],
    "maths": np.random.randint(50, 100, 5),
    "physics": np.random.randint(50, 100, 5),
    "chem": np.random.randint(50, 100, 5)
})
df

   name  maths  physics  chem
0   Ace     59       88    56
1  Riya     52       62    54
2   Sam     69       87    56
3  Tina     83       60    53
4   Raj     98       87    60

In [12]:
print(df["name"])
print(df[["name"]])

0     Ace
1    Riya
2     Sam
3    Tina
4     Raj
Name: name, dtype: object
   name
0   Ace
1  Riya
2   Sam
3  Tina
4   Raj

In [14]:
df.iloc[0]          # first row
df.iloc[-1]         # last row
df.iloc[1:4]        # rows 1, 2, 3 (end is NOT included)

   name  maths  physics  chem
1  Riya     52       62    54
2   Sam     69       87    56
3  Tina     83       60    53

In [25]:
df.loc[0]                    # row with label 0
df.loc[1:3]                  # rows labelled 1, 2, 3 (end IS included here)

   name  maths  physics  chem
1  Riya     52       62    54
2   Sam     69       87    56
3  Tina     83       60    53

In [22]:
df[df["maths"] > 70]                          # maths greater than 70
df[(df["maths"] > 70) & (df["chem"] > 50)]    # AND condition
df[(df["maths"] > 90) | (df["chem"] > 90)]    # OR condition
df[df["name"] == "Ace"]                       # exact match

  name  maths  physics  chem
0  Ace     59       88    56

In [36]:
# Only numeric columns can be averaged, so select them first
marks = df[["maths", "physics", "chem"]]

marks.mean()               # mean of EACH COLUMN (axis=0 is default)
marks.mean(axis=0)         # same as above, written explicitly
marks.mean(axis=1)         # mean of EACH ROW

df["maths"].mean()         # mean of ONE column only
marks.iloc[0].mean()       # mean of ONE row only (first row)
df["maths"].iloc[0].mean() # mean of ONE value only

np.float64(59.0)

In [39]:
marks.sum()          # total of each column
marks.median()       # middle value
marks.std()          # standard deviation
marks.var()          # variance
marks.min()          # smallest
marks.max()          # largest
marks.corr()         # correlation between columns

df["maths"].idxmax()                   # row label of the highest maths score -- serial no of RAJ
df.loc[df["maths"].idxmax(), "name"]   # name of the topper in maths

'Raj'

In [ ]:
# --- Add a new column ---
df["total"] = df["maths"] + df["physics"] + df["chem"]  
df["passed"] = df["maths"] > 60          # True / False column

# --- Change an existing column ---
df["maths"] = df["maths"] + 5            # add 5 to everyone

# --- Drop (remove) a column ---
df = df.drop(columns=["passed"])

# --- Sort ---
df = df.sort_values("total", ascending=False)   # highest total first

# --- Add a new row ---
new_row = pd.DataFrame({"name": ["Zed"], "maths": [80]})
df = pd.concat([df, new_row], ignore_index=True)

0    250.0
1    217.0
2    208.0
3    201.0
4    173.0
5      NaN
Name: total, dtype: float64

In [49]:
summary_df = pd.DataFrame({
    "name": df["name"],
    "average": df[["maths", "physics", "chem"]].mean(axis=1)
})
summary_df.to_csv("new_data.csv", index=False)